title: Un blog para frikis
description:  Espero que disfrutes con este blog.
permalink: ':title/'
baseurl: "/" 
url: "https:/Frikis.github.io" 
site-twitter: 


author: De mayor quiero ser friki  
author-img: clon.jpg 
about-author: Aqui los frikis dejamos nuestras diferencias atras y nos unimos como un megafriki.
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 




# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
